# Generated by Django 5.2 on 2025-04-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctorName", models.CharField(max_length=50)),
                ("speciality", models.CharField(max_length=50)),
                ("education", models.CharField(max_length=100)),
                ("experience", models.IntegerField()),
                ("contact", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=100)),
                ("available_time", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
        ),
    ]
