# Generated by Django 5.2 on 2025-04-12 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("bloodGroup", models.CharField(max_length=5)),
                ("allergies", models.TextField()),
                ("medication", models.TextField()),
                ("surgeries", models.TextField()),
                ("notes", models.TextField()),
                (
                    "doctorAssigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctor.doctor"
                    ),
                ),
            ],
        ),
    ]
